name: Debricked scan

on: [push]

jobs:
  vulnerabilities-scan-production:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Fingerprint files
        run: |
          cd yarn
          rm package.json
          rm yarn.lock
          cd ..
          cd npm 
          npm install
          rm package.json
          rm package-lock.json
          cd node_modules
          debricked fingerprint
          cd ..
          mv node_modules/debricked.fingerprints.txt .
          
      - name: Run Scan
        run: |
          debricked scan
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}

  vulnerabilities-scan-staging:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Fingerprint files
        run: |
          cd yarn
          rm package.json
          rm yarn.lock
          cd ..
          cd npm 
          npm install
          rm package.json
          rm package-lock.json
          cd node_modules
          debricked fingerprint
          cd ..
          mv node_modules/debricked.fingerprints.txt .
          
      - name: Run Scan
        run: |
          debricked scan
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN_STAGING }}
          DEBRICKED_URI: 'https://staging.debricked.com'
